name: Dobong-Life server CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  S3_BUCKET_NAME: dobong-life-s3
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      # run: ./gradlew clean build
      run: ./gradlew clean build -x test # 테스트 Skip

    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
        
    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

    - name: Create application.yml
      env:
        APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
      run: |
        mkdir -p ./src/main/resources
        echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml
      shell: bash

    # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy
      
    - name: Make zip file
      run: zip -r ./dobong.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./dobong.zip s3://$S3_BUCKET_NAME/

    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      run: |
        aws deploy create-deployment \
        --application-name dobong-codedeploy \
        --deployment-group-name dobong-codedeploy-group \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=dobong-life-s3,bundleType=zip,key=dobong.zip \
        --region ap-northeast-2
